# Generated by Django 3.2.4 on 2021-06-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS_web_app', '0005_alter_user_empid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default='', max_length=20, verbose_name='Employee Department'),
        ),
    ]
