# Generated by Django 3.2.4 on 2021-07-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS_web_app', '0007_alter_user_empid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Person_name', models.CharField(default='null', max_length=100)),
                ('Contact_number', models.CharField(default='null', max_length=100)),
                ('Courier_Name', models.CharField(default='null', max_length=100)),
                ('Tracking_ID', models.CharField(default='null', max_length=100)),
                ('dc_number', models.IntegerField()),
                ('received_from', models.CharField(max_length=40)),
                ('no_of_boxes', models.IntegerField()),
                ('DC_date', models.DateField(null=True)),
                ('without_document', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='null', max_length=128)),
                ('comments', models.CharField(default='if no enter your comment', max_length=100)),
                ('Damage_Shipment', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='null', max_length=128)),
                ('comments1', models.CharField(default='if no enter your comment', max_length=100)),
                ('Short_Shipment', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='null', max_length=128)),
                ('comments2', models.CharField(default='if no enter your comment', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UnitDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serial_no', models.CharField(max_length=123)),
                ('part_no', models.CharField(max_length=123)),
                ('Description', models.TextField(max_length=322)),
                ('Word_order_no', models.CharField(max_length=345)),
                ('With_accessories_choice', models.CharField(choices=[('y', 'YES'), ('n', 'NO')], max_length=134)),
                ('Number_Of_Accessories', models.IntegerField()),
                ('Repeat_Repair_Choice', models.CharField(choices=[('y', 'YES'), ('n', 'NO')], max_length=134)),
                ('Repeat_Repair_Comment', models.TextField(max_length=123)),
            ],
        ),
    ]
