# Generated by Django 3.2.4 on 2021-07-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS_web_app', '0008_logisticdetail_unitdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logisticdetail',
            old_name='Short_Shipment',
            new_name='Short_or_Excess_Shipment',
        ),
        migrations.AlterField(
            model_name='logisticdetail',
            name='Contact_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='logisticdetail',
            name='Courier_Name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='logisticdetail',
            name='Person_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='logisticdetail',
            name='Tracking_ID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='logisticdetail',
            name='comments',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='logisticdetail',
            name='comments1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='logisticdetail',
            name='comments2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
