# Generated by Django 3.2.4 on 2021-07-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMS_web_app', '0009_auto_20210715_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logisticdetail',
            old_name='Contact_number',
            new_name='Contact_Number',
        ),
        migrations.RenameField(
            model_name='logisticdetail',
            old_name='DC_date',
            new_name='DC_Date',
        ),
        migrations.RenameField(
            model_name='logisticdetail',
            old_name='dc_number',
            new_name='DC_Number',
        ),
        migrations.RenameField(
            model_name='logisticdetail',
            old_name='Person_name',
            new_name='DS_comments',
        ),
        migrations.RenameField(
            model_name='logisticdetail',
            old_name='no_of_boxes',
            new_name='Number_Of_Boxes',
        ),
        migrations.RenameField(
            model_name='logisticdetail',
            old_name='comments',
            new_name='Person_Name',
        ),
        migrations.RenameField(
            model_name='logisticdetail',
            old_name='received_from',
            new_name='Received_From',
        ),
        migrations.RenameField(
            model_name='logisticdetail',
            old_name='comments1',
            new_name='SE_comments',
        ),
        migrations.RenameField(
            model_name='logisticdetail',
            old_name='comments2',
            new_name='WD_comments',
        ),
        migrations.RenameField(
            model_name='unitdetail',
            old_name='Serial_no',
            new_name='Part_Number',
        ),
        migrations.RenameField(
            model_name='unitdetail',
            old_name='part_no',
            new_name='Serial_Number',
        ),
        migrations.RenameField(
            model_name='unitdetail',
            old_name='With_accessories_choice',
            new_name='With_Accessories_Choice',
        ),
        migrations.RenameField(
            model_name='unitdetail',
            old_name='Word_order_no',
            new_name='Word_Order_Number',
        ),
    ]
