# Generated by Django 3.2.4 on 2021-07-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS_web_app', '0010_auto_20210715_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticdetail',
            name='DC_Date',
            field= models.CharField(default='null',max_length=50),
        ),
        migrations.AlterField(
            model_name='logisticdetail',
            name='Damage_Shipment',
            field=models.CharField(choices=[('', '-'), ('y', 'Yes'), ('n', 'No')], default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='logisticdetail',
            name='Short_or_Excess_Shipment',
            field=models.CharField(choices=[('', '-'), ('y', 'Yes'), ('n', 'No')], default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='logisticdetail',
            name='without_document',
            field=models.CharField(choices=[('', '-'), ('y', 'Yes'), ('n', 'No')], default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='unitdetail',
            name='Repeat_Repair_Choice',
            field=models.CharField(choices=[('', '-'), ('y', 'Yes'), ('n', 'No')], max_length=134),
        ),
        migrations.AlterField(
            model_name='unitdetail',
            name='With_Accessories_Choice',
            field=models.CharField(choices=[('', '-'), ('y', 'Yes'), ('n', 'No')], max_length=134),
        ),
    ]
