# Generated by Django 3.2.4 on 2021-07-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS_web_app', '0021_alter_logisticdetail_dc_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticdetail',
            name='Contact_Number',
            field=models.CharField(default='null', max_length=15),
        ),
        migrations.AlterField(
            model_name='logisticdetail',
            name='Courier_Name',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='logisticdetail',
            name='Person_Name',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='logisticdetail',
            name='Tracking_ID',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
