# Generated by Django 3.2.4 on 2021-07-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS_web_app', '0024_auto_20210722_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Circle', models.CharField(max_length=100)),
            ],
        ),
    ]
